branches:
  - production
  - name: staging
    prerelease: rc
plugins:
  -
    - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: refactor
          release: patch
        - type: style
          release: patch

npmPublish: false
