export const LOCAL_STORAGE_KEY = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
}

export const QUERY_KEY = {
  GET_HOME_BANNERS: 'GET_HOME_BANNERS',
  GET_REWARDS: 'GET_REWARDS',
  GET_HOME_GAMES: 'GET_HOME_GAMES',
  GET_HOME_GAMES_BLOG: 'GET_HOME_GAMES_BLOG',
  GET_HOME_EVENT_WIDGET: 'GET_HOME_EVENT_WIDGET',
}
