export const LOCAL_STORAGE_KEY = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
}

export const QUERY_KEY = {
  GET_HOME_BANNERS: 'GET_HOME_BANNERS',
  GET_REWARDS: 'GET_REWARDS',
  GET_HOME_GAMES: 'GET_HOME_GAMES',
  GET_HOME_GAMES_BLOG: 'GET_HOME_GAMES_BLOG',
  GET_HOME_EVENT_WIDGET: 'GET_HOME_EVENT_WIDGET',
  GET_HOME_NFT_COLLECTION: 'GET_HOME_NFT_COLLECTION',

  GET_BEST_LISTING_BY_NFT: 'QUERY_KEY:GET_BEST_LISTING_BY_NFT',
  GET_ALL_COLLECTION_OFFERS: 'QUERY_KEY:GET_ALL_COLLECTION_OFFERS',

  GET_COIN_USD_PRICE: 'QUERY_KEY:GET_COIN_USD_PRICE',
}
